### ISSUE TITLE
Merge test, lint and commitlint workflows

### ISSUE THREAD

**Issue by browniebroke** [browniebroke/django-codemod#214]
We have 3 workflows that run during CI at the moment: `test.yml`, `lint.yml` and `commitlint.yml`. We could simplify this by merging them into a single `ci.yml` workflow, with 3 separate jobs `test`, `lint` and `commitlint`.

**Comment by iamshnoo** [comment]
Hi! I was taking a look at this issue and wanted to ask for clarification regarding the triggering event for the combined workflow.

The test job and lint job uses the following triggering ```on``` event.
```yaml
on:
  push:
    branches:
      - master
  pull_request:
```

The commit linter meanwhile uses a different one.
```yaml
on: [push]
```

How should I be handling this within the same workflow file, i.e what should be the triggering ```on``` event?

**Comment by browniebroke** [comment]
Hey, thanks for bringing this up! That's a good question, and the answer is that we want to trigger the CI workflow like the current test and lint jobs:

```
on:
  push:
    branches:
      - master
  pull_request:
```
